plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false